### ISSUE TITLE
Classification Levels

### ISSUE THREAD

**Issue by gcharest** [canada-ca/open-source-logiciel-libre#24]
Source code needs to be clearly identified as Unclassified.

Security: should not be an obstacle for OSS (use or release).

**Comment by gcharest** [comment]
Ashley: Input is welcomed, participation is encouraged! Please stay engaged with us, we need you!

**Comment by gcharest** [comment]
We'll need to loop back with TBS Cyber to make sure we set clear guidance. Calvin Riding had great points in his presentation. Let's leverage industry and Government best practices find within our own departments.

**Comment by leif81** [comment]
Has there been input from DND? From what I understand their default position is that modifications to software for DND become Canadian Controlled Goods. If that's the case, I'd love to know what hoops to jump through to release UNCLASS contributions back to external open source projects.

**Comment by ShadeWyrm** [comment]
The following should provide details on the stance taken for code :

In order for source code to potentially be deemed protected, it would have to contain any of the following information:

Information that is deemed Classified
Information obtained in confidence
Information about federal-provincial affairs
Information about international affairs and defence
Information about law enforcement and investigations
Information about the safety of individuals
Information about the economic interests of Canada
Personal information
Third party information
Advice about certain aspects of operations of government
Information about testing procedures, tests, and audits
Information that is subject to solicitor-client privilege
Information that is subject to statutory prohibitions
Certain types of information held by the Canadian Broadcasting Corporation and Atomic Energy of Canada Limited
Confidences of the Queen’s Privy Council for Canada
It is highly unlikely that developers would intentionally include such information in their source code. As a result, source code is considered unclassified unless the developer has included, inadvertently or otherwise, information that falls under the items listed above.

Where feasible, this information should be removed from the source code to increase the ability for code to be shared.

---
Ergo, all code regardless of who developed it is Unclassified by default.

Closing, if you feel more information is required please feel free to re-open! :)
