### ISSUE TITLE
Include an opening on what is Open Source?

### ISSUE THREAD

**Issue by NoureenS** [canada-ca/open-source-logiciel-libre#49]
Could link to [Open Source Definition](https://en.wikipedia.org/wiki/The_Open_Source_Definition) on Wikipedia and also give a short description. 

Example:
Open Source is a software development practice that allows you to example, modify and redistribute modified source code and use the software however one wishes. As long as the source code is open, the provider doesn't have to provide the following and can charge for:

- Customer Support
- Cloud Based Services
- Managed Solutions for Large Scale Deployments
- Packaged Software (software you don't have to compile from the source)
- UI using artwork/typeface (art is not software)

**Comment by gcharest** [comment]
Good point, will add definitions to the guides!

One of the challenges to add external resources is that for official purposes (these will most likely end up on here https://www.tbs-sct.gc.ca/pol/index-eng.aspx), we don't typically link to external resources since they may change without our knowledge.

The Open First Whitepaper, however, did point to many of these external resources and can definitely be supplemented: https://github.com/canada-ca/Open_First_Whitepaper

**Comment by gcharest** [comment]
Also, all information in the guidelines has to be bilingual, Frend and English.

**Comment by ShadeWyrm** [comment]
As per a recommendation by legal, we explicitly define Open Source now.

Closing. :)
